var dictionary = [["A", " "],
["a", " not"],
["á", " 1. preposition; <á> on, upon; at, in; to, towards; by means of; during; in the manner of 2. noun, feminine; nominative singular of <á> river 3. verb; 3rd singular present of <eiga> own, have, possess; have in marriage; have the power to; have claim to; have duty to"],
["á brott", " away (adv)"],
["á flot", " adverb; <á flot> afloat"],
["á móti", " preposition; <á> on, upon; at, in; to, towards; by means of; during; in the manner of + noun; dative singular neuter of <mót> meeting"],
["á-brandr", " gold, 'river-fire' (m)"],
["a-lengðar", " for the future"],
["á-liðinn", " far-spent; at áliðnum degi - at the end of the day"],
["áæggia", " urge on (v)"],
["ábyrgð", " liability (f)"],
["Aðalraðr konungr", " Æthelred (personal name), King Æthelred II (the unready), b. c. 966 AD – d. 1016 AD (m)"],
["Aðalsteinn", " Athalstan (personal name), king of England, b. 895 AD - d. 939 AD (m)"],
["Aðalsteins", " proper noun, masculine; genitive singular of <Aðalsteinn> Athalstan, king of England"],
["Adam", " proper noun, masculine; accusative singular of <Adam> Adam"],
["áðr", " adverb; <áðr> before, first; until"],
["aðra", " adjective; accusative singular feminine of <annarr> other, another; second, next; one (of two)"],
["aðrir", " adjective; nominative plural masculine of <annarr> other, another; second, next; one (of two)"],
["æ", " 1. adverb; <æ> ever, always; forever 2. alas!"],
["æ, ē", " ever, always; forever (adv)"],
["æcki", " adverb; <ekki> not, by no means"],
["ædle", " origin, extraction (n)"],
["æðra", " fear; despair, despondency; words or sounds of despair (f)"],
["æfter", " after (prep)"],
["æggiar", " noun, feminine; accusative plural of <egg> edge"],
["áeggjun", " egging on, urging (f)"],
["ægir", " sea; Óðins æ - poetry, poem (m)"],
["æighi", " adverb; <eigi> not"],
["æinn", " adjective; nominative singular masculine of <einn> one; a certain, particular"],
["æitt", " adjective; accusative singular neuter of <einn> one; a certain, particular"],
["æja", " graze; rest (v)"],
["ælli", " noun, feminine; accusative singular of <elli> old age"],
["æn", " but, and (conj)"],
["Ænghla", " proper noun, masculine plural; genitive of <Englar> Angles, the English"],
["Ængland", " proper noun, neuter; accusative singular of <England> England"],
["Ænglar", " proper noun, masculine plural; nominative of <Englar> Angles, the English"],
["ænn", " adverb; <enn> still; also; yet; further; again; moreover; even"],
["æpte(r)", " after (prep); afterwards (adv)"],
["æptedøme", " example (n)"],
["ær", " who (pron)"],
["Æsir", " 1. noun, masculine; nominative plural of <áss> god 2. Æsir, one of the two major groups of gods (m pl)"],
["æsta", " request, ask for (v)"],
["æt-lēpæ", " adopt (v)"],
["ætla", " expect, look for, intend (to do), purpose, mean; fated; think, consider (to be); ætla til - count upon, believe; ætla til fundar við - intend to meet one; ætlask fyrir - intend (v)"],
["ætlaði", " verb; 1st or 3rd singular past of <ætla (að)> think, consider (to be); expect, look for; intend (to do)"],
["ætlan", " intent (f)"],
["ætlat", " past participle; nominative singular neuter of <ætla (að)> think, consider (to be); expect, look for; intend (to do)"],
["ætluðu", " verb; 3rd plural past of <ætla (að)> think, consider (to be); expect, look for; intend (to do)"],
["ætlun", " 1. estimate, opinion (f) 2. noun, feminine; dative singular of <ætlun> estimate, opinion"],
["ætt", " direction, point of compass, region; family, line, lineage, stock, tribe, descent, race; ancestry; í æ Vǫlsunga - like the race of the Volsungs (f)"],
["ætt-leifð", " patrimony (f)"],
["ættaðr", " descended; hvar hann var æ - what was his origin (v)"],
["ættangr", " family calamity or misfortune (m)"],
["ættar-tala", " genealogy (f)"],
["Ættar-tǫlu", " proper noun, feminine; accusative singular of <Ættar-tala> genealogy"],
["ættir", " noun, feminine; nominative or accusative plural of <ætt> direction, region; family, line; stock, tribe; ancestry"],
["æva", " adverb; <æva> never; not at all"],
["ævagi", " adverb; <ævagi> never"],
["ævi", " life; age, time; life-story; alla ævi - for all time, forever (f)"],
["æztr", " highest"],
["af", " preposition or adverb; <af> out of, from; with; concerning; because of"],
["af hafi", " foreign, from abroad"],
["af því at", " conjunction; <af_því_at> because, for"],
["af-hús", " room at the side (n)"],
["af-skipta", " cut off from inheritance (adj)"],
["áfakliga", " exceedingly"],
["afar", " extremely (adv)"],
["afarmenni", " big or strong man (n)"],
["afbragð", " outstanding example; afbragð þeira manna allra - the most outanding of all those men (n)"],
["afbrigði", " deviation, transgression, offense (n)"],
["afklæða", " undress (v)"],
["afl", " 1. hearth, fireplace or chimney of a forge 2. strength; physical strength, might, power; rammr at afli - extremely strong (n)"],
["afl-raun", " trial of strength (f)"],
["afla", " noun, masculine; accusative plural of <afl> hearth, fireplace or chimney of a forge"],
["aflæ", " beget (v)"],
["afli", " 1 power, aid (m) 2. noun, neuter; dative singular of <afl> strength"],
["afráð", " noun, neuter; accusative singular of <afráð> payment, tribute; heavy penalty or toll"],
["afreksmaðr", " outstanding or exceptional man (m)"],
["afroð", " loss; gjalda afroð - suffer loss (n)"],
["afrœkjask (kt)", " neglect"],
["afrœktusk", " verb; 3rd plural past middle of <afrœkjask (kt)> neglect"],
["afskræmi-liga", " hideously (adv)"],
["afskræmiliga", " adverb; <afskræmiliga> hideously"],
["aftr", " preposition; <eptir> after, behind; for, to obtain; along; according to; in succession to"],
["ágæti", " celebration, glory; gøra at ágætum - give great praise to (n); glorious deeds (n pl)"],
["ágætliga", " honorably (adv)"],
["ágætr", " excellent; famous (adj)"],
["ágirni", " noun, feminine; accusative singular of <ágirni> greed"],
["Agli", " proper noun, masculine; dative singular of <Egill> Egil"],
["áhyggja", " care, anxiety (f)"],
["Ái", " proper noun, masculine; nominative singular of <Ái> Ai, Great grandfather"],
["ák", " verb; 1st singular present of <eiga> own, have, possess; have in marriage; have the power to; have claim to; have duty to + pronoun; nominative singular of <ek> I"],
["ak-taug", " halyard (ship/sailing term)"],
["aka", " drive (v)"],
["ákafamaðr", " an aggressive man (m)"],
["ákafi", " heat; vehemence (m)"],
["ákafliga", " exceedingly, very, vehemently, impetuously (adv)"],
["ákafr", " fierce, vehement (adj)"],
["ákaft", " adverb; <ákaft> greatly"],
["akarn", " acorn (n)"],
["akkeri", " anchor (n)"],
["akr", " field, crop"],
["aktaumr", " brace (ship/sailing term)"],
["ál", " leather strap (f)"],
["al-búinn", " quite prepared"],
["al-byggðr", " completely settled"],
["al-grár", " all gray"],
["al-mög(h)e", " people, commons (m)"],
["ala", " bear, give birth to; bring up, raise (children); feed (v)"],
["albryniaðer", " adjective; nominative plural masculine of <albryniaðr> all clad in mail, in a byrnie"],
["albryniaðr", " mailed, all clad in mail, in a byrnie"],
["ald", " age, generation (f)"],
["alda", " noun, feminine; genitive plural of <ǫld> age; mankind, humanity, world; (pl.) men, human beings"],
["aldartal", " age, count of time"],
["aldartali", " noun, neuter; dative singular of <aldartal> count of time, age"],
["aldinn", " old, aged (adj)"],
["aldør-döm", " old-age (m)"],
["aldr", " age; lifetime; old age; long period of time; vera við aldr - be well on in years (m)"],
["aldregi", " adverb; <aldgregi, aldri> never"],
["aldri", " adverb; <aldgregi, aldri> never"],
["aldrnari", " fire, the nourisher of life (m)"],
["álfheimr", " Álfheim, World of the Elves (m)"],
["Alföðr", " All-Father, i.e., Odin"],
["Álfr", " proper noun, masculine; nominative singular of <Álfr> Alf, Elf"],
["alheimskr", " completely foolish (adj)"],
["alicarl", " fatso, fat churl"],
["alin", " Old Icelandic ell (about half a yard); unit of value, typically of woolen cloth"],
["alinn", " past participle; nominative singular masculine of <ala> give birth to, bear; feed"],
["alit", " appearance, feature, aspect (n)"],
["all-góðr", " very good"],
["all-ógurligr", " most terrible (adj)"],
["all-reiðr", " very angry (adj)"],
["all-sannr", " quite true (adj)"],
["all-sterkr", " very strong (adj)"],
["all-vel", " very well"],
["alla", " adjective; accusative singular feminine or plural masculine of <allr> all, whole; every"],
["allan", " adjective; accusative singular masculine of <allr> all, whole; every"],
["allar", " adjective; accusative plural feminine of <allr> all, whole; every"],
["allfrægr", " very famous(adj)"],
["allfriðr", " very beautiful (adj)"],
["allharða", " adjective; accusative singular feminine of <allharðr> severe, violent"],
["allharðr", " severe, violent (adj)"],
["allir", " adjective; nominative plural masculine of <allr> all, whole; every"],
["alllítill", " adjective; nominative singular masculine of <alllítill> very little"],
["allmikill", " very great (adj)"],
["allmikit", " adjective; accusative singular neuter of <allmikill> very great"],
["allr", " adjective; nominative singular masculine of <allr> all, whole; every"],
["allra", " adjective; genitive plural masculine of <allr> all, whole; every"],
["allri", " adjective; dative singular feminine of <allr> all, whole; every"],
["allstórum", " enormously (adv)"],
["allt", " 1. adjective; nominative or accusative singular neuter of <allr> all, whole; every 2. completely, entirely; everywhere; allt til Orneykja - all the way to the Orkney islands; alt til þess - right up to that point; allt upp undir right up under"],
["allvaldr", " sovereign ruler (m)"],
["allvegliga", " splendidly"],
["almætr", " said by all"],
["almannavegr", " main road, route normally followed (m)"],
["almáttigr", " adjective; nominative singular masculine of <almáttigr> almighty"],
["almenniligr", " universal"],
["almenningr", " full levy of men (m)"],
["almosa", " alms-giving (f)"],
["almr", " bow; elm (m)"],
["álög", " dues or taxes (n pl)"],
["álpt", " swan (f)"],
["Alrekr", " Alrek (personal name)"],
["alsekr", " full outlaw (m)"],
["alsnotr", " very wise, sagacious, wise (of a woman) (adj)"],
["alsvartr", " pure black (adj)"],
["alt", " adjective; nominative singular neuter of <allr> all, whole; every"],
["alvæpni", " armed (fully); a complete equipment of arms"],
["Alþiófr", " proper noun, masculine; nominative singular of <Alþiófr> Althjof, Great thief"],
["alþyða", " people (all the people), the majority of the people, the public, the common people (f)"],
["ámæli", " blame, reproach (m)"],
["ámælissamr", " shameful"],
["ámátcar", " adjective; nominative plural feminine of <ámáttugr> tremendously or overwhelmingly powerful; fearsome; loathesome"],
["ámátt", " adjective; nominative singular neuter of <ámáttr> terrible, loathsome"],
["ámáttr", " terrible, loathsome"],
["ámáttugr", " powerful (tremendously or overwhelmingly); fearsome; loathesome"],
["ambátt", " handmaid, maidservant; bondwoman (f)"],
["ambótt", " bondwoman (f)"],
["amma", " grandmother (f)"],
["Án", " 1. without (prep) 2. proper noun, masculine; nominative singular of <Án> An 3. An (personal name)"],
["Ánarr", " proper noun, masculine; nominative singular of <Ánarr> Anar"],
["andask", " die (v)"],
["anddyri", " vestibule of hall (n)"],
["anddyrit", " noun, neuter; accusative singular of <anddyri> vestibule of hall + definite article; accusative singular neuter of <inn> the"],
["andi", " spirit, breath (m)"],
["andlát", " death (n)"],
["andlit", " face (n)"],
["andskoti", " enemy, adversary (m)"],
["andvarða", " commit (v)"],
["angan", " noun, neuter; nominative singular of <angan> delight, joy"],
["Angantýr", " proper noun, masculine; nominative singular of <Angantýr> Angantyr"],
["angr", " grief, sorrow (m)"],
["angra", " distress; distinguish (v)"],
["annan", " adjective; accusative singular masculine of <annarr> other, another; second, next; one (of two)"],
["annarr", " adjective; nominative singular masculine of <annarr> other, another; second, next; one (of two)"],
["annarr hvárr", " one or another; either"],
["annars", " adjective; genitive singular masculine or neutral of <annarr> other, another; second, next; one (of two)"],
["annask", " take care of (v)"],
["annat", " adjective used as substantive; nominative singular neuter of <annarr> other, another; second, next; one (of two)"],
["annt", " eager, anxious (adj)"],
["anzuara (aþ)", " answer (v)"],
["aptan", " noun, masculine; accusative singular of <aptann> evening"],
["aptann", " evening, the separation of day from night (m)"],
["aptr", " back; aft; again; vara atir - remain behind (adv)"],
["aptrgǫngu-maðr", " one who walks after death (m)"],
["ár", " 1. year; (good) season (n) 2. adverb; <ár> early, in the early morning; of yore, long ago"],
["ár-óss", " mouth of a river (m)"],
["áræði", " courage, daring (n)"],
["árangr", " season (m)"],
["áreið", " noun, feminine; accusative singular of <áreið> cavalry charge"],
["arf", " inheritance (n)"],
["arfa", " noun, masculine; accusative singular of <arfr> inheritance"],
["arfa-sáta", " heap of chickweed (f)"],
["árferð", " season, harvest (f)"],
["arfi", " heir (m)"],
["arfr", " inheritance (m)"],
["argr", " cowardly, womanish, effeminate, (passively) homosexual (adj)"],
["ari", " eagle (m)"],
["ári", " noun, neuter; dative singular of <ár> year; (good) season"],
["Arinbjǫrn", " proper noun, masculine; nominative singular of <Arinbjǫrn> Arinbjorn"],
["ármaðr", " steward (m)"],
["armr", " 1. arm (m) 2. poor, unfortunate, unhappy; vile, wretched, wicked (adj)"],
["Arngrímr", " Arngrim (personal name)"],
["Arngríms", " proper noun, masculine; genitive singular of <Arngrímr> Arngrim"],
["árom", " noun, neuter; dative plural of <ár> year; (good) season"],
["arr", " unwary (adj)"],
["ársæll", " fortunate as to the seasonal harvest; allra konunga ársælstr - of all kings the most harvest-fortunate (adj)"],
["árvænn", " promising a good seaonal harvest (adj)"],
["arwæ", " heir (m)"],
["ás-meginn", " divine strength (n)"],
["ása", " noun, masculine; genitive plural of <áss> god"],
["ásamt", " together (adj)"],
["Ásbrú", " another name for Bifröst (f)"],
["asc", " noun, masculine; accusative singular of <askr> ash tree; spear; Ash"],
["Ásgarðr", " Asgard, the residence or fortress of the gods (m)"],
["ásjá", " help, aid, protection; inspection; appearance, shape (f)"],
["aska", " ashes (f)"],
["askr", " ash, ash tree; ash spear; small ship; the great ash tree Yggdrasill (m)"],
["áss", " 1. noun, masculine; nominative singular of <áss> god 2. god (m); Æsir - one of the two major groups of gods (m pl) 3. beam, timber, pole; ship"],
["ást", " love, affection (f)"],
["ástgir", " adjective; nominative plural masculine of <ástugr> loving, benevolent"],
["ástir", " love, affection (f pl)"],
["ástugr", " loving, benevolent (adj)"],
["ásuauðr", " ewe (m)"],
["ásynja", " goddess (f)"],
["at", " 1. conjunction; <at> that 2. preposition; <at> to, towards, against; at, in; from; according to; regarding; concerning; after 3. not"],
["at augum", " preposition; <at> to, towards, against; at, in; from; according to; regarding; concerning; after + noun, neuter; dative plural of <auga> eye"],
["at því er", " relative; <at_því_er> how; as"],
["atall", " fierce, aggressive, terrible (adj)"],
["atalt", " adjective; nominative singular neuter of <atall> fierce, terrible"],
["atburðr", " occurrence, event; af þessum atburði because of this incident (m)"],
["atdráttr", " provisions; supplies"],
["atferð", " behavior; energy (f)"],
["atferli", " proceeding (n)"],
["atganga", " attack, assault; violence (f)"],
["atgeirinum", " noun, masculine; dative singular of <atgeirr> thrusting spear + definite article; dative singular masculine of <inn> the"],
["atgeirr", " thrusting-spear (m)"],
["atgervi", " man of accomplishments (m)"],
["atgørvi", " ability, talent, accomplishment; at atgørvi in ability (esp physical) (f and n)"],
["atgørvimaðr", " man of accomplishments (m)"],
["átján", " eighteen (num)"],
["atkváma", " arrival (f)"],
["atlaga", " alongside (laying of ships alongside for attack), attack (f)"],
["atmælasamr", " fault-finding"],
["atrið", " movement; hafa alt eitt atrið - do two things in one swift movement, all at once (n)"],
["atriðit", " noun, neuter; accusative singular of <atrið> movement + definite article; accusative singular neuter of <inn> the"],
["atróðr", " rowing towards, rowing against (m)"],
["átrunaðr", " belief (m)"],
["atseta", " residence, royal residence (f)"],
["atsetu", " noun, feminine; genitive singular of <atseta> residence"],
["átta", " eight (num)"],
["átti", " verb; 3rd singular past of <eiga> own, have, possess; have in marriage; have the power to; have claim to; have duty to"],
["áttján", " eighteen (num)"],
["áttjándi", " eighteenth (ord num)"],
["átto", " verb; 3rd plural past of <eiga> own, have, possess; have in marriage; have the power to; have claim to; have duty to"],
["áttrœðr", " adjective; nominative singular masculine of <áttrœðr> eighty years old"],
["áttu", " verb; 3rd plural past of <eiga> own, have, possess; have in marriage; have the power to; have claim to; have duty to"],
["auð", " noun, masculine; accusative singular of <auðr> wealth, riches, treasure; precious objects"],
["auðgom", " adjective; dative singular masculine of <auðigr> wealthy, rich"],
["auði", " noun, masculine; dative singular of <auðr> wealth, riches, treasure; precious objects"],
["auðigr", " rich, wealthy; auðigr at fé - very wealthy (adj)"],
["auðit", " fated (v)"],
["auðna (að)", " fateful, (impers.) fall out by fate"],
["auðnar", " verb; 3rd singular present of <auðna (að)> (impers.) fall out by fate"],
["auðœfi", " wealth, possessions (f)"],
["auðr", " treasure, wealth, riches; precious objects"],
["auðsénn", " evident, easily seen"],
["auðsýnn, auðsynn", " evident, clear"],
["auga", " eye (n)"],
["augabragð", " wink, sidelong glance"],
["augabragði", " noun, neuter; dative singular of <augabragð> wink, sidelong glance"],
["augom", " noun, neuter; dative plural of <auga> eye"],
["auk", " aside from (prep)"],
["auka", " increase, augment; add; exceed, surpass; aukaþis - multiplied (v)"],
["auki", " increase; fœrask í aukana - exert the utmost of one's strength (m)"],
["aura", " noun, masculine; genitive plural of <eyrir> ounce of silver"],
["aurr", " mud (m)"],
["aurvanga", " noun, masculine plural; genitive of <aurvangar> damp or muddy fields"],
["aurvangar", " fields (muddy or damp)"],
["Aurvangr", " proper noun, masculine; nominative singular of <Aurvangr> Aurvang, Mudfield"],
["ausa", " pour; sprinkle; ladle; water; (mid.) stream, flow; ausa bát - bail a boat (v)"],
["ausinn", " past participle; nominative singular masculine of <ausa> ladle; pour; water; (mid.) stream, flow"],
["austan", " adverb; <austan> from the east; east (of); bearing to the east"],
["austmaðr", " noun, masculine; nominative singular of <austmaðr> Easterner, Norwegian"],
["austr", " east (n); eastward (adv)"],
["austrför", " travels to the east (f)"],
["Austri", " proper noun, masculine; nominative singular of <Austri> East"],
["Austrlönd", " the eastern lands; eastern Europe; Russia and the Orient (n pl)"],
["austrvegr", " the east; the Baltic Lands (m)"],
["auvirði", " worthless wretch (m)"],
["auvirðis-maðr", " worthless wretch (m)"],
["ávalt", " always"],
["ávant", " lacking; er ávant - is wanted, needed; þykkir mér á - I think I lack (adj)"],
["ávǫxtr", " increase, growth (m)"],
["awnd", " hatred, envy (f)"],
["B", " "],
["bacraut", " asshole"],
["bað", " verb; 3rd singular past of <biðja> ask; beg; pray; bid"],
["báðir", " adjective; nominative plural masculine of <báðir> both"],
["baðmr", " noun, masculine; nominative singular of <baðmr> tree"],
["báðu", " verb; 3rd plural past of <biðja> ask; beg; pray; bid"],
["báðum", " adjective; dative plural masculine or feminine of <báðir> both"],
["bæði", " 1. also, as well (adv) 2. both, in; bæði … ok - both … and (conj)"],
["bæin", " noun, neuter; accusative singular of <bein> bone; ivory"],
["bær", " house"],
["bæriaz", " verb; infinitive of <berja (barði)> smite, beat; (refl.) fight"],
["bæriz", " verb; 2nd plural present subjunctive middle of <berja (barði)> smite, beat; (refl.) fight"],
["bæsingær", " small hill (m)"],
["bætra", " comparative adjective; nominative singular neuter of <betri> better"],
["bætri", " comparative adjective; accusative singular feminine of <betri> better"],
["bagall", " crozier, episcopal staff"],
["baggi", " bag (m)"],
["bagla", " noun, masculine; accusative plural of <bagall> episcopal staff, crozier"],
["bak", " noun, neuter; accusative singular of <bak> back"],
["bak-borði", " port side, 'back-side' (ship/sailing term)"],
["baka", " bake (v)"],
["bakinu", " noun, neuter; dative singular of <bak> back + definite article; dative singular neuter of <inn> the"],
["bakki", " bank (m)"],
["bál", " noun, neuter; accusative plural of <bál> fire"],
["bálkr", " wall, partition (m)"],
["bamba", " drum (f)"],
["bana", " 1. verb; infinitive of <bana (að)> kill 2. noun, masculine; accusative or genitive singular of <bani> death; cause of death, slayer"],
["bana (að)", " kill (v)"],
["banahǫgg", " death-blow (n)"],
["banamaðr", " killer, executioner, slayer (m)"],
["banasár", " fatal wound, mortal wound, death (n)"],
["band", " band, cord, bond, bind, fetter; the act of binding; (pl) bands, fetters"],
["bani", " death; bane, cause of death, slayer (m)"],
["bann", " prohibition, ban (n)"],
["banna", " verb; 1st singular present of <banna (að)> prohibit, forbid"],
["banna (að)", " ban, forbid, prohibit (v)"],
["bannaði", " verb; 3rd singular past of <banna (að)> prohibit, forbid"],
["bar", " verb; 3rd singular past of <bera> bear, bring, carry; wear; give birth to; overcome; endure; bear (witness)"],
["bardagi", " fight, battle; beating, thrashing (m)"],
["barit", " past participle; nominative singular neuter of <berja (barði, bariðr)> smite, beat; (refl.) fight"],
["barn", " child (n)"],
["barni", " noun, neuter; dative singular of <barn> child"],
["barnœska", " childhood (f)"],
["barr", " foliage, often needles (of pine, etc.) (n)"],
["Barreyjar", " the Barra Isles (f pl)"],
["barsmið", " fight, assault (f)"],
["bati", " advantage (m)"],
["batna", " improve; batnar - one recovers (v)"],
["bátr", " boat (ship's boat)"],
["bauð", " verb; 3rd singular past of <bjóða> offer, provide; command, summon"],
["baug-set", " arm, 'ring seat' (n)"],
["baug-skati", " ring-giving prince (m)"],
["bauga", " noun, masculine; accusative plural of <baugr> ring; coil"],
["baugr", " ring, bracelet, armlet; coil (m)"],
["baulufotr", " foot of a cow"],
["bautarsteinar", " noun, masculine; nominative plural of <bautarsteinn> memorial stone"],
["bautarsteinn", " stone (memorial stone)"],
["Bávǫrr", " proper noun, masculine; nominative singular of <Bávǫrr> Bavor"],
["bazt", " adjective used as substantive; <beztr> best"],
["beðr", " bed (m)"],
["beiða", " ask, beg; ask for, request on one's own behalf (v)"],
["bein", " bone; ivory (n)"],
["beina", " assist (v)"],
["beinahrúga", " bones (heap), bone-pile (f)"],
["beinahrúgu", " noun, feminine; accusative or dative singular of <beinahrúga> heap of bones"],
["beinahrúgunni", " noun, feminine; dative singular of <beinahrúga> heap of bones + definite article; dative singular feminine of <inn> the"],
["beini", " help, benefit (m)"],
["beinum", " noun, neuter; dative plural of <bein> bone; ivory"],
["beiskaldi", " gripe, bitch"],
["beiskr", " bitter, acrid; angry, exasperated; painful, sore (adj)"],
["beita", " sail near the wind, beat"],
["beitiáss", " sailyard, spar (tacking spar) (ship/sailing term)"],
["beiting", " grazing, pasturage (f)"],
["beizl", " bridle (n)"],
["bekk", " noun, masculine; accusative singular of <bekkr> bench"],
["bekk-þili", " boards of the benches, benches (n)"],
["bekkr", " bench (m)"],
["belgr", " pelt, skin of animals taken off whole, skin-bag, bellows, bag (m)"],
["bella", " hit, hurt, dare; venture; belt við - committed against; bellendr - those who take part in (v)"],
["belti", " belt (n)"],
["ben", " wound (mortal) (f)"],
["ben-már", " raven, 'wound-grouse', 'wound-mew' (m)"],
["bengrefill", " wound-engraver (m)"],
["ber", " verb; 1st singular present of <bera> bear, bring, carry; wear; give birth to; overcome; endure; bear (witness)"],
["bera", " bear, bring, carry; wear; give birth to; overcome; endure; bear (witness); bera saman - collect; compare; bera ørendi sin (upp) fyrir - plead one's case before; tell one's errand (v)"],
["berg-risi", " hill-giant (m)"],
["berja", " verb; infinitive of <berja (barði)> smite, beat; (refl.) fight"],
["berja (barði, bariðr)", " strike, beat smite, beat; berjask - fight (v)"],
["berk", " verb; 1st singular present of <bera> bear, bring, carry; wear; give birth to; overcome; endure; bear (witness) + pronoun; nominative singular of <ek> I"],
["berling", " beam (ground beam for tent)"],
["berr", " 1. naked, bare; unsheathed (of a sword) (adj) 2. verb; 3rd singular present of <bera> bear, bring, carry; wear; give birth to; overcome; endure; bear (witness)"],
["berrat", " verb; 3rd singular present of <bera> bear, bring, carry; wear; give birth to; overcome; endure; bear (witness) + enclitic adverb; <at> not"],
["berserkjanna", " noun, masculine; genitive plural of <berserkr> berserk + definite article; genitive plural masculine of <inn> the"],
["berserkr", " berserker (m)"],
["berserksgangr", " fury of a berserker, going berserk (m)"],
["betr", " better; more (adv)"],
["betra", " comparative adjective; nominative singular neuter of <betri> better"],
["betri", " better (adj)"],
["beygja", " 1. bend, arch (v) 2. affliction (f)"],
["beysta", " bruise, beat (v)"],
["beytill", " horse-prick (m)"],
["bezt", " best (adv)"],
["beztr", " best (adj)"],
["beztu", " adjective; weak <beztr> best"],
["biæuær", " beaver (m)"],
["biæuær-thræl", " beaver that is thrall (m)"],
["bið", " verb; 1st singular present of <biðja> ask; beg; pray; bid"],
["biða (að)", " await, wait for, remain, abide; suffer, undergo (v)"],
["biðaðe", " verb; 1st singular past subjunctive of <biða (að)> await"],
["biðja", " ask, beg, command, tell, pray; bid; ask for; ask for a woman in marriage on behalf of another; biðjum - I ask for myself; biðja gera - command to be made (v)"],
["biðjum", " verb; 1st plural present of <biðja> ask; beg; pray; bid"],
["bifaðisk", " verb; 3rd singular past middle of <bifask (ð, að)> tremble; move; march"],
["bifask (ð, að)", " shake, tremble, quake, move, be moved; march (v)"],
["Bifröst", " Bifrost, the rainbow bridge that connects Miðgarðr and Ásgarðr (f)"],
["bikkja", " female dog, bitch (f)"],
["bikkjuna", " noun, feminine; accusative singular of <bikkja> bitch, dog + definite article; accusative singular feminine of <inn> the"],
["bil", " moment (of time) (n)"],
["bila", " fail (v)"],
["bilstyggr", " energetic; quickly moved"],
["bilt", " startled (adj)"],
["binda", " dress; bind, tie, fasten; bind up (a wound); pledge; binda í - bind to, bind on (v)"],
["biǫð, bjǫð", " fields; land (n pl)"],
["bióða", " verb; infinitive of <bjóða> offer, provide; command, summon"],
["bioðom", " noun, feminine; dative plural of <biǫð> land"],
["birgðir", " provisions (f pl)"],
["birgja", " provide or supply (v)"],
["birta", " display (v)"],
["biskup", " bishop (m)"],
["biskups", " noun, masculine; genitive singular of <biskup> bishop"],
["biskupum", " noun, masculine; dative plural of <biskup> bishop"],
["bita", " cut (v)"],
["bíta", " bite, bite through; rip apart; cut (v)"],
["bitr", " brave, biting, keen, fierce (adj)"],
["Bívǫrr", " proper noun, masculine; nominative singular of <Bívǫrr> Bivor"],
["bjalla", " bell (f)"],
["bjarg", " rock, stone, boulder; cliff; crag; mountain (n)"],
["bjarga", " save, help (v)"],
["bjarkan", " birch (n)"],
["bjarn-báss", " pit (for catching bears) (m)"],
["bjarn-dýr", " bear (n)"],
["Bjarnadóttir", " Bjorn's daughter (personal name) (f)"],
["Bjarnarfjöðr", " Bjorn's Fjord (place name) (m)"],
["Bjarni", " Bjarni (personal name) (m)"],
["bjartr", " bright (adj)"],
["bjǫð", " fields, land(s) (n pl)"],
["bjóða", " invite, order, command; bid; offer; provide; challenge; threaten; call upon, summon; offer, provide; bjóða heim - invite to one's house; bjóða upp - give up; bjóðja sætt - offer reconciliation; bjóðja at sætt - offer to for reconciliation (v)"],
["bjóðja", " challenge (v)"],
["bjóðr", " giver (m)"],
["bjóðum", " verb; 1st plural present of <bjóða> offer, provide; command, summon"],
["bjǫllur", " noun, feminine; accusative plural of <bjalla> bell"],
["bjór-ker", " beer-goblet (n)"],
["bjǫrg", " 1. means of subsistence (f) 2. noun, neuter; accusative plural of <bjarg> rock; mountain"],
["bjǫrn, björn", " bear (m) birnir (pl)"],
["bjórr", " beer; piece of leather (m)"],
["bjósk", " verb; 3rd singular past middle of <búa> be ready, prepare, secure"],
["blá", " adjective; weak dative singular masculine of <blár> blue; black"],
["Bláinn", " Blain (personal name)"],
["Bláins", " proper noun, masculine; genitive singular of <Bláinn> Blain"],
["blakkr", " black; dark (adj)"],
["bland", " in; í bland - among (prep)"],
["blanda (blett, -að)", " blend, mix (v)"],
["blandask", " have dealings with (v)"],
["blandit", " past participle; accusative singular neuter of <blanda (blett, : að)> blend, mix"],
["blár", " blue; dark, black (adj)"],
["blása", " blow; blásinn - bare, stripped by the wind (v)"],
["blatqnn", " black tooth"],
["blautr", " soft; soaked, wet (adj)"],
["bleikr", " white fair"],
["blesóttom", " adjective; dative singular masculine of <blesóttr> having a white blaze on the forehead"],
["blesóttr", " marked, having a white mark on the forehead"],
["bleyta", " soft, swampy patch of ground (f)"],
["bliða", " friendliness (f)"],
["bliðr", " happy, pleasant; gracious (adj)"],
["blindr", " blind (adj)"],
["blóð", " blood (n)"],
["blóð-refill", " sword point (m)"],
["blóði", " noun, neuter; dative singular of <blóð> blood"],
["bloðorn", " blood-eagle"],
["blóðs", " noun, neuter; genitive singular of <blóð> blood"],
["blóðugr", " bloody (adj)"],
["blóm", " flower"],
["blót", " sacrifice; heathen (n)"],
["blóta", " worship; worship with sacrifice; sacrifice, sacrifice in worship; curse (v)"],
["blunda", " shut the eyes, doze (v)"],
["bö-land", " inhabited land (n)"],
["bǫð-reifr", " rejoicing in battle"],
["bǫð, boð", " feast, festival; summons; battle (n)"],
["boða", " preach (v)"],
["boðet", " past participle; nominative singular neuter of <bjóða> offer, provide; command, summon"],
["boðorð", " noun, neuter; accusative singular of <boðorð> commandment"],
["boðsmaðr", " guest (m)"],
["Bǫðvar", " proper noun, masculine; accusative singular of <Bǫðvarr> battle, Bothvar"],
["Bǫðvarr", " proper noun, masculine; nominative singular of <Bǫðvarr> battle, Bothvar"],
["Bǫðvars", " proper noun, masculine; genitive singular of <Bǫðvarr> battle, Bothvar"],
["bœgi", " noun, masculine; dative singular of <bœgr> shoulder"],
["bœgr", " shoulder"],
["bœkr", " noun, feminine; accusative plural of <bók> book"],
["bœn", " prayer, request (f)"],
["bœnum", " noun, masculine; dative singular of <bœr> farmhouse, farmstead; farm, landed estate; town + definite article; dative singular masculine of <inn> the"],
["bœr", " farmhouse, farmstead; farm, landed estate; town (m)"],
["bœta", " better, compensate, make compensation, make amends for (v)"],
["bœtr", " noun, feminine; accusative plural of <bót> compensation, atonement"],
["bogastrengr", " bow-string (m)"],
["bogi", " bow (m)"],
["bóglína, boglina", " bowline (ship/sailing term)"],
["bógr", " shoulder, shoulder of an animal (m)"],
["bók", " book (f)"],
["bokki", " buck, fellow (used as a manner of address); bokki sæll - good fellow, good sire, boss (m)"],
["ból", " lair (n)"],
["bǫl, böl", " grief, sorrow, misfortune (n)"],
["boløx", " broad-axe (f)"],
["bölvasmiðr", " contriver of mischief, misfortune (m)"],
["Bǫmburr", " proper noun, masculine; nominative singular of <Bǫmburr> Bombur"],
["bónda-lið", " yeoman army (n)"],
["bóndason", " farmer's son, son of a yeoman, son of a bóndi (m)"],
["bóndi", " noun, masculine; nominative singular of <bóndi> yeoman, franklin; husband"],
["bor-móðr", " bored with a gimlet"],
["borð", " board, strake, hull, plank; side of a ship; table; food, upkeep; rim; margin between rim and liquid; á borð - on one side (of a ship); fyrir borð - overboard (f)"],
["borð-meiri", " rising higher above the sea"],
["borðveggr", " noun, masculine; nominative singular of <borðveggr> board wall, wall made of planks"],
["borg", " castle, fortress, stronghold; town; funeral pyre (f)"],
["borgar", " noun, feminine; genitive singular of <borg> castle, fortress; funeral pyre"],
["borgar-górð", " building of a stronghold (f)"],
["borgar-hlið", " gateway of a stronghold (n)"],
["borgarmaðr", " garrisoned soldier; townsman (m)"],
["borna", " past participle of <bera> bear, bring, carry; wear; give birth to; overcome; endure; bear (witness)"],
["bornom", " noun, neuter; dative plural of <barn> child"],
["bót", " bettering, cure, remedy; adornment; (pl) compensation, atonement; at botúm - as atonement (f)"],
["bqllr", " ball, glans penis"],
["brá", " eyelash (f)"],
["bráðgörr", " matured early in life, precocious (adj)"],
["bráðr", " sudden, hasty, impatient; hot-tempered; (adj)"],
["bráðum", " soon, shortly (adv)"],
["bragða (að)", " move, stir (v)"],
["bragðar", " verb; 3rd singular present of <bragða (að)> move, stir"],
["bragþáttr", " poetry (m)"],
["braka (að)", " crack, creak (v)"],
["brakaði", " verb; 3rd singular past of <braka (að)> crack, creak"],
["brandr", " blade; brand, firewood (piece of) (m)"],
["brann", " verb; 3rd singular past of <brenna> (intrans.) burn, be on fire"],
["brátt", " soon, suddenly; brátt er - as soon as (adv)"],
["brattr", " steep (adj)"],
["brauð", " bread (n)"],
["brauðgǫrð", " bread-making (f)"],
["braudnefr", " breadnose"],
["brauflutning", " carrying off (f)"],
["braut", " road (f); í braut - away (adv)"],
["brauto", " noun, feminine; dative singular of <braut> road"],
["brauzk", " verb; 3rd singular past of <brjóta> (trans.) break, destroy; distribute; (mid.) exert oneself"],
["bréf", " letter (n)"],
["bregða", " move quickly; draw (sword), brandish (a weapon); break (faith or an oath); turn, alter, change; break off, leave off, give up; bregða við - ward off with, parry with; bregða upp - lift up, raise (to strike); bregða bui - give up one's farm; bregða sér - flinch; bregðask - fail, come to nothing; deceive, disappoint, bregðask i - shapechange, turn into; bregðr við - one is afraid; brá mǫnnum mjǫk við þat - they were greatly startled at this (v)"],
["breið-øx", " axe with a long blade (f)"],
["breiða", " spread; stretch; display (v)"],
["Breiðablik", " Breidablik, the hall of the god Baldr (n)"],
["breiðara", " more broadly (adv)"],
["breiðr", " broad; breiðir steinar - brooches; bíta breiðara - take bigger bites"],
["brekka", " hillside, slope"],
["brendo", " verb; 3rd plural past of <brenna (d)> (trans.) burn, light, set on fire"],
["brendr", " past participle; nominative singular masculine of <brenna (d)> (trans.) burn, light, set on fire"],
["brenna", " verb; infinitive of <brenna> (intrans.) burn, be on fire"],
["brenna (d)", " burn, light, set on fire; brenna inna - burn (a person) in his house (vt)"],
["brennanda", " present participle; accusative singular masculine of <brenna> (intrans.) burn, be on fire"],
["brenni", " verb; 3rd present subjunctive of <brenna (d)> (trans.) burn, light, set on fire"],
["brennr", " verb; 3rd singular present of <brenna> (intrans.) burn, be on fire"],
["brennu", " verb; 3rd singular imperative of <brenna (d)> (trans.) burn, light, set on fire"],
["bresta", " burst, break, crash; bresta niðr - crash down; bresta upp - burst forth (v)"],
["breyta", " act; do (v)"],
["brim-sker", " rock on which waves break (n)"],
["brimill", " seal (a variety of); brimills vǫllr - sea (the seal's field) (m)"],
["Brimir", " Brimir, sword; (name of a sword); (name of a giant)"],
["Brimis", " proper noun, masculine; genitive singular of <Brimir> sword; (name of a sword); (name of a giant)"],
["brióstom", " noun, neuter; dative plural of <brjóst> breast"],
["brjóst", " breast, chest (n)"],
["brjósti", " noun, neuter; dative singular of <brjóst> breast"],
["brjóta", " break, break up, break open, break into; destroy; violate; deal out, distribute; exert oneself; brjóta skip - be wrecked (ship); brjóta til rikis - fight for the kingdom; brjóta upp grjót - pull up stones; exert oneself, struggle; brjótask til rikis - fight for the kingdom (v)"],
["brodd-flǫtr", " shield, 'field of spear-points' (m)"],
["broddr", " point of the spear, spike (m)"],
["bróðer", " noun, masculine; nominative singular of <bróðir> brother"],
["bróðir", " brother (m)"],
["bróðor", " noun, masculine; genitive singular of <bróðir> brother"],
["bróðurgjöld", " wergeld, ransom, or compensation for a dead brother (n pl)"],
["brœðr", " noun, masculine; dative singular of <bróðir> brother"],
["brœkr", " breeches (f pl)"],
["brǫkon", " noun, feminine; dative singular of <brǫkon> clashing"],
["brǫkon, brokun", " clashing (f)"],
["brǫndom", " noun, masculine; dative plural of <brandr> piece of firewood"],
["brotinn", " past participle; nominative singular masculine of <brjóta> (trans.) break, destroy; distribute; (mid.) exert oneself"],
["brotna (að)", " break, be broken (vi)"],
["brotnaði", " verb; 3rd singular past of <brotna (að)> (intrans.) break, be broken"],
["brott", " 1. away, off (adv) 2. noun, feminine; nominative singular of <braut> road"],
["brott-hlaup", " running away (n)"],
["brottkvaðning", " dismissal, sending away (f)"],
["brottu", " noun, feminine; accusative singular of <braut> road"],
["brottvaðning", " dismissal, sending away (f)"],
["brú", " bridge; causeway built over swampy ground (f)"],
["brúð-fé", " bridal gift (n)"],
["brúðar", " noun, feminine; genitive singular of <brúðr> bride, young married woman; wife"],
["brúðr", " bride, young married woman; wife (f)"],
["brugðit", " past participle; accusative singular neuter of <bregða> move quickly; throw; draw (sword)"],
["brullaup, bruð-laup", " wedding, wedding feast; ganga at brullaupi með - marry (n)"],
["brún", " eye-brow (f)"],
["brúnáss", " ridge-beam (m)"],
["brúnásunum", " noun, masculine; dative plural of <brúnáss> ridge: beam + definite article; dative plural masculine of <inn> the"],
["bruni", " fire, heat (m)"],
["brúnmóálöttr", " brownish-gray with a dark stripe down the back"],
["brunn", " brown (adj)"],
["brunni", " noun, masculine; dative singular of <brunnr> burn, spring, well"],
["brunnr", " well; spring; burn (m)"],
["brunnu", " verb; 3rd plural past of <brenna> (intrans.) burn, be on fire"],
["brusi", " goat (he-goat)"],
["brut-pæningar", " toll paid on departure (m pl)"],
["bryggja", " gangway; pier; landing-stage; bridge (f)"],
["brynia", " noun, feminine; nominative singular of <brynja> coat of mail"],
["bryniulausir", " adjective; nominative plural masculine of <brynjulauss> without mail, unprotected"],
["brynja", " mail (coat of); chain-mail shirt (f)"],
["brynju", " noun, feminine; dative singular of <brynja> coat of mail"],
["brynjulauss", " mail-less, without mail, unprotected (adj)"],
["brynjur", " noun, feminine; accusative plural of <brynja> coat of mail"],
["brýnn", " clear; urgent"],
["brýtæ", " break, violate (v)"],
["bryti", " bailiff, steward (m)"],
["bú", " home, house, household; farming, farm, dwelling; estate; livestock (n)"],
["búa", " live (in a place), dwell, inhabit, live; prepare, make ready; array, dress; dwell; have a household, keep house; be, be ready; búa til - prepare for; búa um - arrange, set up; búa um sik - make one's bed; búa um skip - prepare a ship (for the winter); búið heilir - dwell in peace, farewell, have a household, keep house; búa í skapi - be on one's mind; búit - equipped; búinn til - ready for, prepared, able; búa við - prepared to, ready for; svá búit - in such matters, as matters stand; við svá búit - without more ado; búask - prepare, get oneself ready; búask til - make ready for, prepare oneself for; búask til ferðar - set out; búask um - make oneself secure; encamp, take quarters, be prepared for; expect; (v)"],
["buð", " booth, temporary dwelling (f)"],
["buðlungr", " noun, masculine; nominative singular of <buðlungr> king, prince"],
["buðumk", " verb; 1st singular past middle of <bjóða> offer, provide; command, summon"],
["búfé", " cattle, farm-cattle (n)"],
["bugh", " noun, masculine; accusative singular of <bughr> curve"],
["bughr", " curve; í bugh sklialdr - behind the curved shield (m)"],
["búi", " 1. dweller, inhabitant; neighbor (m) 2. verb; 3rd plural present subjunctive of <búa> be ready, prepare, secure"],
["búin", " past participle; nominative singular feminine of <búa> be ready, prepare, secure"],
["búinn", " ready, prepared (v pp of búa)"],
["búit", " past participle; nominative singular neuter of <búa> be ready, prepare, secure"],
["búiz", " verb; 3rd singular present subjunctive middle of <búa> be ready, prepare, secure"],
["búizk", " past participle; accusative singular neuter middle of <búa> be ready, prepare, secure"],
["buna", " buna (nickname of uncertain meaning, perhaps 'one with ungartered stockings,' i.e. hanging down his leg) (f)"],
["búnaðr", " equipment (m)"],
["burð", " noun, masculine; accusative singular of <burðr> birth"],
["burðr", " birth (m)"],
["burin(n)", " born"],
["burlufótr, burlufotr", " foot (a clumsy foot) (m)"],
["Burr", " 1. son (m) 2. Bur, Odin's father"],
["Burs", " proper noun, masculine; genitive singular of <Burr> Bur, Odin's father"],
["bús-hlutr", " farm implements (m pl)"],
["bús-hœgindi", " help in running a household (n pl)"],
["Búseyra", " Buseyra, a giantess killed by Thor (f)"],
["búss", " wood (a type of wood) (m)"],
["bústaðr", " dwelling-place (m)"],
["bý", " 1. home, house, household; farm; estate (n) 2. bee; unda bý - arrow, 'wound bees' (n)"],
["býfluga", " bee (f)"],
["bygð", " noun, feminine; dative singular of <bygð> dwelling, settlement"],
["bygði", " verb; 3rd singular past of <byggja (gð)> dwell, settle; build, inhabit"],
["bygðisk", " verb; 3rd singular past middle of <byggja (gð)> dwell, settle; build, inhabit"],
["bygðu", " verb; 3rd plural past of <byggja (gð)> dwell, settle; build, inhabit"],
["bygghlaða", " barley-barn (f)"],
["byggja (gð)", " dwell; settle; build; inhabit; byggias firir - settle in (v)"],
["byggva", " settle; occupy, inhabit (v)"],
["bylgja", " billow (v)"],
["byrdh", " birth (f)"],
["byrði", " noun, feminine; accusative singular of <byrðr> burden, load"],
["byrðr", " burden, load (f)"],
["byrja", " begin (v)"],
["byrja (að)", " begin; enter upon (v)"],
["byrr", " fair wind, favorable wind; gaf þeim vel byri - they got a favorable wind (m)"],
["bytta", " bucket, pail (f)"],
["C", " "],
["callaðr", " past participle; nominative singular masculine of <kalla> call, cry out; name; say, declare"],
["comnir", " past participle; nominative plural masculine of <koma> come, arrive; reach; obtain; occur"],
["cornband", " prohibition of corn trade (n)"],
["cost", " noun, masculine; accusative singular of <kostr> choice, alternative; offer; chance, opportunity; money available; match, marriage; condition, quality; terms"],
["cristin-dömer", " Christianity"],
["cristna", " baptize (v)"],
["cuna", " wife (f)"],
["cvað", " verb; 3rd singular past of <kveða> say, declare; utter, say in verse; recite; utter a cry"],
["D", " "],
["dáð", " 1. deed (f) 2. courage, energy (f)"],
["dæll", " gentle, easy (to manage) (adj)"],
["dælt", " adjective; nominative singular neuter of <dæll> gentle, easy (to manage)"],
["dæma", " judge (v)"],
["dag", " noun, masculine; accusative singular of <dagr> day"],
["daga", " dawn (v)"],
["dagan, dǫgun", " daybreak (f)"],
["dagmál", " day time, a roughly three hour time of the day beginning about 9:00 a.m.; breakfast time (n)"],
["dagmála-staðr", " position of the sun at dagmál (m)"],
["dagr", " day, daylight, dawn (m); daylight hours, days, time (m pl); í dag, í dagh - today; at the present day; daghum - by day; døgr - day, a 24 hour span of time"],
["dagr-verðr", " day-meal, the chief meal, eaten about 9:00 a.m. (m)"],
["dagsmark", " day-mark, time of day (n)"],
["Dáinsleif", " Dainsleif, the name of Hógni's sword, Dain's inheritance"],
["dala", " noun, masculine; accusative plural of <dalr> dale, dell, valley"],
["dálkr", " pin (m)"],
["dalr", " dale, dell, valley (m)"],
["Dana-konungr", " King of the Danes (m)"],
["Danir", " Danes (m pl)"],
["Danmörk", " Denmark (f)"],
["Danskr", " Danish (adj)"],
["danzleikr", " dance, dancing-song (m)"],
["dāræ", " fool, buffoon (m)"],
["darraðr", " spear (m)"],
["datt", " verb; 3rd singular past of <detta> drop, fall"],
["dauða", " adjective; accusative plural masculine of <dauðr> dead"],
["dauða-maðr", " doomed man; vilja hafa at dauðamanni - seek one's life (m)"],
["dauðadagr", " death-day (m)"],
["dauði", " death; lifs né dauða - neither in life nor in death (m)"],
["dauðir", " adjective; nominative plural masculine of <dauðr> dead"],
["dauðr", " noun, masculine; nominative singular of <dauðr> death"],
["daufi", " deaf-mute, stupid (adj)"],
["daufr", " adjective used as substantive; nominative singular masculine of <daufr> deaf"],
["dautt", " adjective; nominative singular neuter of <dauðr> dead"],
["dccclxx", " numeral; nominative plural of <sjau hundruð ok þrír tigir> eight hundred seventy"],
["deila", " disagreement, contention (f)"],
["deila (d)", " divide; distinguish; quarrel, contend; deila við - contend with (v)"],
["deild", " litigation, quarrel (f)"],
["deili", " noun, neuter; accusative plural of <deili> (pl.) details"],
["dēl", " part (m)"],
["detta", " drop, fall (v)"],
["deyja", " die, pass away (v)"],
["digr", " big, stout; thick; deep (adj)"],
["digri", " adjective; weak nominative singular masculine of <digr> big, stout; thick; deep"],
["djarfan", " adjective; accusative singular masculine of <djarfr> bold, daring"],
["djarfliga", " boldly (adv)"],
["djarfr", " bold, daring (adj)"],
["djúpauðigr", " deep-minded (adj)"],
["djúpr", " deep (adj)"],
["djúpum", " adjective; dative plural masculine of <djúpr> deep"],
["djúpvitr", " deep-witted, resourceful (adj)"],
["dó", " verb; 3rd singular past of <deyja> die, pass away"],
["dødher, døther", " death (m)"],
["dœgr, døgr", " day, 24 hour span of time (n)"],
["dœma", " judge; proclaim (v)"],
["dœya", " verb; infinitive of <deyja> die, pass away"],
["dofni", " dopey"],
["dǫgg, dögg", " dew (f)"],
["dǫggvar", " noun, feminine; nominative plural of <dǫgg> (sg. and pl.) dew"],
["dǫglingr", " prince (m)"],
["dǫgum", " noun, masculine; dative plural of <dagr> day"],
["dǫgun, dagan", " daybreak (f)"],
["Døkkálfar", " the Dark Elves (m pl)"],
["døkkr", " dark (adj)"],
["dólg, dolg", " battle; þrúðr dolga - battle, the valkyrja Hild (n)"],
["Dólgþrasir", " Dolgthrasir (personal name)"],
["dǫlum", " noun, masculine; dative singular of <dalr> dale, dell, valley"],
["dómari", " judge (m)"],
["dómr", " judgment; reputation, fame; court; heilagr dómr - sacred relic (m)"],
["dómstaðr", " place where court is held (m)"],
["dómstóll", " judgment seat (m)"],
["dóttir", " noun, feminine; nominative singular of <dóttir> daughter"],
["dótturson", " grandson, daughter's son (m)"],
["dǫuðar-orð", " death tidings; sæghia dǫuðar-orð - slay one in a fight (n)"],
["dǫuðarorð", " noun, neuter; accusative singular of <dǫuðarorð> tidings of death"],
["draga", " pull, draw, drag, haul; draga seil upp - hoist sail; draga et sér - collect; draga til - compel, induce; draga frá - clear away; draga undan - escape; draga á vetur - feed through the winter (v)"],
["dragi", " slowpoke"],
["dragreip", " halyard (ship/sailing term)"],
["dráp", " killing, murder (n)"],
["drasill", " horse (poetic) (m)"],
["draug", " noun, masculine; accusative singular of <draugr> undead man, ghost"],
["draugr", " ghost, 'undead man'; tree-trunk (m)"],
["draugum", " noun, masculine; dative plural of <draugr> undead man, ghost"],
["draumblæti", " pride, haughtiness (n)"],
["draumr", " dream (m)"],
["Draupnir", " Draupnir, dripper, a gold ring possessed by Odin with the ability to multiply itself"],
["dreccr", " verb; 3rd singular present of <drekka> drink"],
["dregit", " past participle; accusative singular neuter of <draga> draw, haul"],
["dreifa (ð)", " spread, scatter; sprinkle; dreifask - be spread out (v)"],
["dreifðisk", " verb; 3rd plural past middle of <dreifa (ð)> scatter (dat.); besprinkle (acc.)"],
["dreki", " dragon-ship (m)"],
["drekka", " drink; drekka af - empty; drekka af horninu inn þriðja drykinn - empty the horn at the third draught (v)"],
["drekkja (kt)", " drown (dat.)"],
["drekti", " verb; 3rd singular past of <drekkja (kt)> drown (dat.)"],
["drengiliga", " manfully (adv)"],
["drengiligr", " brave, valiant (adj)"],
["drengja", " noun, masculine; genitive plural of <drengr> (gallant) fellow; warrior"],
["drengr", " warrior; bold man, gallant fellow (m)"],
["drengskapr", " noun, masculine; nominative singular of <drengskapr> nobility, courage"],
["drepa", " verb; infinitive of <drepa> smite, strike; knock; kill, slay"],
["drepi", " verb; 3rd singular subjunctive of <drepa> smite, strike; knock; kill, slay"],
["drepinn", " past participle; nominative singular masculine of <drepa> smite, strike; knock; kill, slay"],
["drepit", " past participle; accusative singular neuter of <drepa> smite, strike; knock; kill, slay"],
["dreyma", " dream (v)"],
["dreyra", " bleed, ooze (of blood from a slight wound) (v)"],
["dreyri", " blood (m)"],
["dreyrugr", " blood-stained (adj)"],
["drif", " throng (v)"],
["drifa", " 1. drive (vt) 2. crowd, throng, drift, hurry, rush (vi)"],
["drífa", " verb; 3rd plural present of <drífa> drive; crowd, throng; rush"],
["driúgt", " adjective used as substantive; accusative singular neuter of <drjúgr> lasting, ample, substantial"],
["drjúgr", " substantial, lasting, ample; verða drúgari - be of more avail; drjúgt manna - a good number of men (adj) drjúgjum - greatly (adv)"],
["drjúpa", " drip (v)"],
["drók", " verb; 1st singular past of <draga> draw, haul + pronoun; nominative singular of <ek> I"],
["dróttin", " noun, masculine; accusative singular of <dróttinn> leader of the host, lord"],
["dróttinn", " lord, leader of the host (m)"],
["dróttning", " queen (f)"],
["droyma (d)", " appear in a dream (v)"],
["drúpa", " droop (v)"],
["drykk", " noun, masculine; accusative singular of <drykkr> draught, drink"],
["drykkja", " drinking (f)"],
["drykkr", " drink, draught (m)"],
["drykkyumaðr", " drinker (m)"],
["dúði", " toss (v)"],
["dúfa", " dove, pigeon (f)"],
["duga", " help, aid, be useful, be of avail, be of assistance; be safe for; do, show prowess; gott at duga - good (easy) to help; duga verr - come off badly, fare worse (in a contest) (v); suffice (vi)"],
["dugi", " verb; 3rd plural present subjunctive of <duga> help, aid, be of avail, be of assistance"],
["dugir", " verb; 3rd singular present of <duga> help, aid, be of avail, be of assistance"],
["dugira", " verb; 3rd singular present of <duga> help, aid, be of avail, be of assistance + enclitic adverb; <a> not"],
["dugr", " ability, skill, prowess; boldness, fearlessness, courage, doughtiness (m)"],
["dul", " reserve, folly; conceit"],
["duna", " noise (thunderous noise) (f)"],
["duna (að)", " resound (v)"],
["dunði", " resound; whir (v)"],
["dunur", " noun, feminine; accusative plural of <duna> thunderous noise"],
["dura", " noun, feminine; genitive plural of <dyrr> door, doorway"],
["Durinn", " proper noun, masculine; nominative singular of <Durinn> Durin"],
["durom", " noun, feminine; dative plural of <dyrr> door, doorway"],
["durum", " noun, feminine; dative plural of <dyrr> door, doorway"],
["durunum", " noun, feminine; dative plural of <dyrr> door, doorway + definite article; dative plural feminine of <inn> the"],
["Dvalinn", " proper noun, masculine; nominative singular of <Dvalinn> Dvalin, Delayer"],
["Dvalins", " proper noun, masculine; genitive singular of <Dvalinn> Dvalin, Delayer"],
["dvelja", " slow, stop (v)"],
["dveljask", " verb; infinitive middle of <dveljask (dvalðisk)> stay; be delayed"],
["dveljask (dvalðisk)", " stay; be delayed (v)"],
["dverga", " noun, masculine; accusative or genitive plural of <dvergr> dwarf"],
["dvergar", " noun, masculine; nominative plural of <dvergr> dwarf"],
["dvergr", " dwarf; fibula (m)"],
["dvǫl", " delay (f)"],
["dyja (dúði)", " shake, toss (v)"],
["dylja (dulði)", " deceive oneself; keep on in ignorance of; vera dulinn - be unaware of; ganga duliðr - be mistaken; (v)"],
["dyljask", " verb; infinitive middle of <dylja (dulði)> keep on in ignorance of; (mid.) deceive oneself"],
["dynja", " din, thunder, resound, whir, whistle (of wings), whizz; pour, shower (v)"],
["dýr", " wild beast; animal; deer (n)"],
["dýr-vǫrðr", " door-keeper (m)"],
["dýra-mergr", " marrow of animals (m)"],
["dyrð, dyrk", " glory (f)"],
["dýrin", " noun, neuter; nominative plural of <dýr> (wild) animal + definite article; nominative plural neuter of <inn> the"],
["dýrinu", " noun, neuter; dative singular of <dýr> (wild) animal + definite article; dative singular neuter of <inn> the"],
["dýrit", " noun, neuter; nominative singular of <dýr> (wild) animal + definite article; nominative singular neuter of <inn> the"],
["dyrnar", " noun, feminine; accusative plural of <dyrr> door, doorway + definite article; accusative plural feminine of <inn> the"],
["dyrr", " door, doorway (f pl)"],
["dýrr", " expensive, dear; precious (adj)"],
["dýrs-hjarta", " beast's heart (n)"],
["dýrsins", " noun, neuter; genitive singular of <dýr> (wild) animal + definite article; genitive singular neuter of <inn> the"],
["dýrt", " adjective; accusative singular neuter of <dýrr> dear, expensive; precious"],
["dys", " grave, cairn (f)"]
];



var glossary = []

for (i=0; i<dictionary.length; i++){
	var pair = dictionary[i];
	var word = pair[0].trim();
	var definition = pair[1];
	var z = '<p><a name="'+word+'"><strong>'+word+'</strong>'+definition+'</a></p><a name="'+word+'">';
	glossary.push(z);
};

window.onload = function () {
    alert("hello world!");
    glossary.forEach(function(entry) {
			e.innerHTML += entry;
		});
};

